# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-d relaxed]
  - repo: https://gitlab.com/smop/pre-commit-hooks.git
    rev: df034f88cf92b394e6f00a78fa97a2aa4e270e60
    hooks:
      - id: check-gitlab-ci
        name: GitLab CI/CD configuration check
        description: Validates .gitlab-ci.yml file
        entry: pre_commit_hooks/check-gitlab-ci
        language: script
        pass_filenames: false
        files: .gitlab-ci.yml
